---
# Source: superset/charts/redis/templates/master/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: superset-redis-master
  namespace: "superset"
spec:
  #type: ClusterIP
  type: LoadBalancer
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: 6379      
  selector:
    app: superset-redis-master
---
# Source: superset/charts/redis/templates/master/statefulset.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset-redis-master
  namespace: "superset"
spec:
  selector:
    matchLabels:
      app: superset-redis-master
  template:
    metadata:
      labels:
        app: superset-redis-master       
    spec:
      securityContext:
        fsGroup: 1001     
      containers:
        - name: redis
          image: docker.io/bitnami/redis:6.2.6-debian-10-r120
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          command:
            - /bin/bash
          args:
            - -c
            - /opt/bitnami/scripts/start-scripts/start-master.sh
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: REDIS_REPLICATION_MODE
              value: master
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: REDIS_TLS_ENABLED
              value: "no"
            - name: REDIS_PORT
              value: "6379"
          ports:
            - name: redis
              containerPort: 6379
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            # One second longer than command timeout should prevent generation of zombie processes.
            timeoutSeconds: 6
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /health/ping_liveness_local.sh 5
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /health/ping_readiness_local.sh 1
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: start-scripts
              mountPath: /opt/bitnami/scripts/start-scripts
            - name: health
              mountPath: /health
            - name: redis-data
              mountPath: /data
              subPath:
            - name: config
              mountPath: /opt/bitnami/redis/mounted-etc
            - name: redis-tmp-conf
              mountPath: /opt/bitnami/redis/etc/
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: start-scripts
          configMap:
            name: superset-redis-scripts
            defaultMode: 0755
        - name: health
          configMap:
            name: superset-redis-health
            defaultMode: 0755
        - name: config
          configMap:
            name: superset-redis-configuration
        - name: redis-tmp-conf
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: redis-data
          emptyDir: {}